// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtW5dV32ysd3VV_poMsFV4iK8CVl1NiU',
    appId: '1:541981393565:web:9b5f2f0408b2b6b3f14a74',
    messagingSenderId: '541981393565',
    projectId: 'safedriver-1403d',
    authDomain: 'safedriver-1403d.firebaseapp.com',
    storageBucket: 'safedriver-1403d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hdPNltngxkZoVoO6BxoMT3UrMJZw2a0',
    appId: '1:541981393565:android:868651fdac4b841cf14a74',
    messagingSenderId: '541981393565',
    projectId: 'safedriver-1403d',
    storageBucket: 'safedriver-1403d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmN9-4Npo5vHEAjTebDlpUw9y44f2iDc',
    appId: '1:541981393565:ios:83d484ead672b38af14a74',
    messagingSenderId: '541981393565',
    projectId: 'safedriver-1403d',
    storageBucket: 'safedriver-1403d.appspot.com',
    iosBundleId: 'com.example.carSpeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmN9-4Npo5vHEAjTebDlpUw9y44f2iDc',
    appId: '1:541981393565:ios:4d8c8402b720cbfdf14a74',
    messagingSenderId: '541981393565',
    projectId: 'safedriver-1403d',
    storageBucket: 'safedriver-1403d.appspot.com',
    iosBundleId: 'com.example.carSpeed.RunnerTests',
  );
}
